name: Build&Test_GhActions

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Validate REACT_BASE Project
        run: |
          cd react-base
          npm install
          npm build
          cd ../

      - name: Validate REACT_BASE Project
        run: |
          cd next-with-firebase
          yarn install
          yarn build
          cd ../
